server:
  port: 8080

spring:
  application:
    name: kafka-core-producer

  kafka:
    producer:
      bootstrap-servers: localhost:9092

app:
  kafka:
    producer:
      HelloKafkaProducer:
        enabled: false
      FixedRateProducer:
        enabled: false
      KafkaKeyProducer:
        enabled: true
