version: "3"

volumes:
    zookeeper-data: {}
    kafka-data: {}
    zookeeper-logs: {}

networks:
    broker-kafka:
        driver: bridge

services:
    zookeeper:
        container_name: zookeeper
        hostname: zookeeper
        image: confluentinc/cp-zookeeper:7.3.2
        ports:
            - "2181:2181"
        networks:
            - broker-kafka
        volumes:
            - zookeeper-data:/var/lib/zookeeper/data
            - zookeeper-logs:/var/lib/zookeeper/log
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        healthcheck:
            test: nc -z localhost 2181 || exit 1
            interval: 10s
            timeout: 5s
            retries: 3

    kafka-v2:
        image: confluentinc/cp-kafka:7.3.2
        container_name: kafka-v2
        hostname: kafka-v2
        depends_on:
            zookeeper:
              condition: service_healthy
        ports:
            - "9092:9092"
            - "29092:29092"
        networks:
            - broker-kafka
        volumes:
            - kafka-data:/var/lib/kafka/data
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-v2:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_JMX_PORT: 9999

    kafka-ui:
        image: provectuslabs/kafka-ui:v0.7.2
        container_name: kafka-ui
        hostname: kafka-ui
        depends_on:
            - kafka-v2
        restart: always
        ports:
            - "8085:8080"
        networks:
            - broker-kafka
        environment:
            KAFKA_CLUSTERS_0_NAME: local-kafka
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-v2:29092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
