server:
  port: 8081

spring:
  application:
    name: kafka-core-consumer

  kafka:
      consumer:
          bootstrap-servers: localhost:9092
          group-id: kafka-core-consumer-group
          # Start reading from the earliest message if no offset is present for this group
          auto-offset-reset: earliest
